### ISSUE TITLE
feature -> zambrano-1 -> voting -> Boolean voting

### ISSUE THREAD

**Issue by AlvaroRodriguezGarcia-hue** [EGC-zambrano/decide-part-zambrano#57]
**Is your feature request related to a problem? Please describe.**
Many of the votings users may create would be answered by a simple yes/no response, and it would be good to simplify their creation process.

**Describe the solution you'd like**
I would change the Question model to include a question type that adds a "yes" and a "no" option automatically, without allowing any other option.

**Describe alternatives you've considered**
It could be also implemented by making a different BooleanQuestion model, but it would be much harder to implement and it would duplicate too much code.

**Additional context**

**Comment by pabpercab1** [comment]
**Bug found in the implementation of the feature.**
When attempting to add more than two QuestionOptions to a boolean voting configuration, the system encounters a 500 Internal Server Error. It should also be checked whether questions with only one option are adequately addressed the same way as the ones with more than 2.

To Reproduce
Steps to reproduce the behaviour:

    Navigate to the Question section.
    Create a new question, selecting Boolean voting as the question type.
    Add more than two options to the question.
    Click on save.

Expected behaviour
To enhance user experience and improve error handling, consider providing a more appropriate HTTP error code such as 400, 401, or 405. This adjustment would ensure a clearer indication of the issue to the user while allowing the application to handle the error more effectively.

Possible solution (optional)
Revise the error handling related to exceeding the allowed number of options for Boolean voting. Modify the ValueError handling to manage out-of-range options more gracefully. This may involve implementing specific error codes (e.g., 400 Bad Request) and appropriate error messages to guide users in creating questions within the allowed parameters.

**Comment by pabpercab1** [comment]
**Bug found in the implementation of the feature.**
When attempting to create boolean voting with the white voting option, it does not appear to work because of the current implementation of boolean voting.

To Reproduce
Steps to reproduce the behaviour:

    Navigate to the Question section.
    Create a new question, selecting Boolean voting as the question type and check VoteBlanck.
    Create the question and a vote.
    See how only appear the boolean voting and not the white voting.

Expected behaviour
It should appear as an option with the white voting option.
